language: php

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer update -n
  - "mysql -e 'create database laminas_test;'"
  - ./vendor/bin/doctrine-module orm:schema-tool:create
  - ./vendor/bin/codecept build

script:
  - './vendor/bin/codecept run functional,doctrine -v'
